finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('about/', views.about, name='about'),
    # comic routes
    path('comics/', views.comics_index, name='index'),
    path('comics/<int:comic_id>/', views.comics_detail, name='detail'),
    path('comics/create/', views.ComicCreate.as_view(), name='comics_create'),
    path('comics/<int:pk>/update/', views.ComicUpdate.as_view(), name='comics_update'),
    path('comics/<int:pk>/delete/', views.ComicDelete.as_view(), name='comics_delete'),
    # add log
    path('comics/<int:comic_id>/add_log/', views.add_log, name='add_log'),
    #add photos
    path('comics/<int:comic_id>/add_photo/', views.add_photo, name='add_photo'),
    #associate funko with comic
    path('comics/<int:comic_id>/assoc_funko/<int:funko_id>/', views.assoc_funko, name = 'assoc_funko'),
    # add funko
    path('funkos/', views.FunkoList.as_view(), name = 'funkos_list'),
    path('funkos/create/', views.FunkoCreate.as_view(), name = 'funkos_create'),
    path('funkos/<int:pk>/', views.FunkoDetail.as_view(), name = 'funkos_detail'),
    path('funkos/<int:pk>/update/', views.FunkoUpdate.as_view(), name = 'funkos_update'),
    path('funkos/<int:pk>/delete/', views.FunkoDelete.as_view(), name = 'funkos_delete'),
    # users
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
ORDERS = (
    ('D','Download'),
    ('R', 'Rental'),
    ('P', 'Paperback')
)
class Funko(models.Model):
    name = models.CharField(max_length=500)
    price = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    img = models.CharField(max_length=500)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("funkos_detail", kwargs={"pk": self.id})
    

class Comic(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    genre = models.CharField(max_length=25)
    published = models.CharField(max_length=15)
    img = models.TextField(max_length=500)
    funkos = models.ManyToManyField(Funko)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={"comic_id": self.id})
    
class Log(models.Model):
    date = models.DateField('Purchase Date')
    order = models.CharField(
        max_length=1,
        choices = ORDERS,
        default = ORDERS[0][0]
    )

    comic = models.ForeignKey(Comic, on_delete = models.CASCADE)

    def __str__(self):
        return f"{self.get_order_display()} on {self.date}"

class Meta:
    ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for comic_id: {self.comic_id} @{self.url}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ##https://docs.djangoproject.com/en/3.2/topics/files/
    ## django required installation of pillow, a library of processing images from PIP
    ## ImageField is a filefield with uploads restricted to image formats only... attributes consists of width, height and other attributes that are available to FileField.
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        ##overwrite the function of the parent class with super(). 
        super().save(*args, **kwargs)


     

main_app/forms.py
from django.forms import ModelForm
from django import forms ## a form class describes a form and determines how it works and appears.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Log, Profile

class LogForm(ModelForm):
    class Meta:
        model = Log
        fields = ['date','order']

class UserSignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']

##forms.ModelForm automatically created form from models, to also avoid duplications
## Nxt configuarion will be to manually create a form by using forms.form
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

main_app/views.py
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from .forms import UserSignupForm, LogForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os
import uuid
import boto3
from .models import Comic, Log, Funko, Photo

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request, 'about.html')

def comics_index(request):
    comics = Comic.objects.all()
    return render(request, 'comics/index.html', {'comics':comics})

@login_required
def comics_detail(request, comic_id):
    comic = Comic.objects.get(id = comic_id)
    return render(request, 'comics/detail.html', {'comic': comic})

class ComicCreate(LoginRequiredMixin,CreateView):
    model = Comic
    fields = ['title','author','genre','img','published']
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)

    success_url = '/comics/'

class ComicUpdate(LoginRequiredMixin,UpdateView):
    model = Comic
    fields = ['title','author','genre','published']

class ComicDelete(LoginRequiredMixin,DeleteView):
    model = Comic
    success_url = '/comics/'

@login_required
def comics_detail(request, comic_id):
    comic = Comic.objects.get(id=comic_id)
    funkos_related = Funko.objects.exclude(id__in = comic.funkos.all().values_list('id'))
    log_form = LogForm()
    return render(request, 'comics/detail.html', {
        'comic':comic, 'log_form': log_form,
        'funkos':funkos_related
    })

@login_required
def add_log(request, comic_id):
    form = LogForm(request.POST)
    if form.is_valid():
        new_log = form.save(commit=False)
        new_log.comic_id = comic_id
        new_log.save()
    return redirect('detail', comic_id = comic_id)

class FunkoList(LoginRequiredMixin,ListView):
    model = Funko

class FunkoDetail(LoginRequiredMixin,DetailView):
    model = Funko

class FunkoCreate(LoginRequiredMixin,CreateView):
    model = Funko
    fields = ['name','img','price','description']

class FunkoUpdate(LoginRequiredMixin,UpdateView):
    model = Funko
    fields = ['name','img','price','description']

class FunkoDelete(LoginRequiredMixin,DeleteView):
    model = Funko
    success_url = "/funkos"

@login_required
def assoc_funko(request, comic_id, funko_id):
    Comic.objects.get(id = comic_id).funkos.add(funko_id)
    return redirect('detail', comic_id=comic_id)

@login_required
def add_photo(request, comic_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url,comic_id=comic_id)
        except:
            print('An error occurred uploading file to S3')
        return redirect('detail', comic_id=comic_id)

def signup(request):
    error_message=''
    if request.method =='POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            ## cleaned_data will always contain a key for fields defined in the Form.
            ## returns a dictionary of validated form input fields and their values
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            user = form.save()
            login(request,user)
            return redirect('home')
        else:
            error_message = 'invalid signup - try again'

    form = UserSignupForm()
    context = {'form':form, 'error_message':error_message}
    return render(request, 'registration/signup.html',context)

@login_required
def profile(request):
    if request.method =='POST':
        ##https://docs.djangoproject.com/en/3.2/intro/tutorial04/
        ## request.POST (call) is a dictionary-like object that allows the user to access submitted data by key name. 
        ## Two seperate variables grabbing the forms and having the arguments be the call and instance of the accessed user model object/profile
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            ## https://docs.djangoproject.com/en/3.2/ref/contrib/messages/
            ## message framework, allows messages to be display filtered by templates or displayed differently in views.
            ## operating like a one-time notification message also known as 'flash messages'
            messages.success(request, f'Account updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'registration/profile.html', context)

main_app/templates/comics/detail.html
{% extends 'base.html' %}
{% block content %}

<div class='container'>
    <div class='row'>
        <div class='col-md-4 p-2'>
            <div class='container'>
                <img class='card-img' src={{ comic.img }}>
            </div>
        </div>
        <div class='col-md-4 p-2 rounded-3'>
            <div class='order-form p-5 container card'>
                <form action="{% url 'add_log' comic.id %}" method="post">
                    {% csrf_token %}
                    {{ log_form.as_p }}
                    <input type='submit' class='btn-primary' value='place order'>
                </form>
                <hr>
                <p>author: {{ comic.author }}</p>
                <p>genre: {{ comic.genre }}</p>
                <p>published: {{ comic.published }}</p>
                <a href="{% url 'comics_update' comic.id %}">edit</a>
                <a href="{% url 'comics_delete' comic.id %}">delete</a>
            </div>
        </div>
        <div class='col-md-4 p-2 rounded-3'>
            <div class='order-form p-5 container card'>
                <table class='table'>
                    <thead>
                        <tr><th>Date:</th><th>type:</th></tr>
                    </thead>
                <tbody>
                {% for log in comic.log_set.all %}
                <tr>
                    <td> {{log.date}} </td>
                    <td> {{log.get_order_display}} </td>
                </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
    <hr>
</div>
<div class='container'>
    <div class='row'>
        <h3>POP related</h3>
        {% if comic.funkos.count %}
        {% for funko in comic.funkos.all %}
        <div class='col-md-2 p-2'>
            <div class='container'>
                <div class="card bg-dark text-white">
                    <img class="card-img rounded-3'" src={{ funko.img }}>
                    <div class='card-img-overlay'>
                        <div class='d-flex flex-row-reverse'>
                            <a href="{% url 'funkos_detail' funko.id %}"><span class="iconify rounded border border-start-0" style='font-size:24px; color:white; background: black' data-icon="mdi:book-information-variant"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5> none related </h5>
        {% endif %}
    </div>
    <hr>
    <div class='row'>
        <h3>all POP</h3>
        {% if funkos.count %}
        {% for funko in funkos.all %}
        <div class='col-md-2 p-2'>
            <div class='container'>
                <div class="card bg-dark text-white">
                    <img class="card-img rounded-3'" src={{ funko.img }}>
                    <div class='card-img-overlay'>
                        <div class='row'>
                            <div class='col-sm-6'>
                                 <form action="{% url 'assoc_funko' comic.id funko.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-dark">add</button>
                                </form>
                            </div>
                            <div class='col-sm-6 d-flex flex-row-reverse'>
                                <a href="{% url 'funkos_detail' funko.id %}"><span class="iconify rounded border border-start-0" style='font-size:24px; color:white; background: black' data-icon="mdi:book-information-variant"></span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>all added!</h5>
        {% endif %}
    </div>
</div>


<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
    const selectEl = document.getElementById('id_order');
    M.FormSelect.init(selectEl)
</script>
{% endblock %}

main_app/templates/comics/index.html
{% extends 'base.html' %}
{% block content %}


<div class='container'>
{% if user.is_authenticated %}
<a href="{% url 'comics_create' %}"><span class="iconify" style='font-size:36px; color: white' data-icon="carbon:add-alt"></span></a>
{% endif %}
  <div class='row '>
  {% for comic in comics %}
    <div class=' col-md-3 mb-5 p-2'>
      <div class='container'>
          <div class="card bg-dark text-white">
            <img class="card-img" src={{ comic.img }}>
            <div class="card-img-overlay">
              <div class="d-flex flex-row-reverse">
                <a href="{% url 'detail' comic.id %}"><span class="iconify rounded border border-start-0" style='font-size:24px; color:white; background: black' data-icon="mdi:book-information-variant"></span></a>
              </div>
            </div>
          </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
<br/>

{% endblock %}